spring:
    application.name: KaiSneaker

    datasource:
        url: jdbc:postgresql://localhost:5432/kaisneaker
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                naming:
                    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    validator-url: 127.0.0.1

server:
  port: 8088